name: Deploy to Ubuntu
on:
  push:
    branches: [ main ]
    workflow_dispatch: # <-- Bu satırı eklersen manuel buton açılır
jobs:
  deploy:
    runs-on: ubuntu-latest
  steps:
      - name: SSH ile Sunucuya Bağlan ve Scripti Çalıştır
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: zekasoft # Burası mutlaka zekasoft olmalı
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/zekasoft/pdf-project
            ./deploy.sh
    
